spring:
  zipkin:
    base-url: http://localhost:9411/ # zipkin server 的请求地址
    discovery-client-enabled: true  # 让 Nacos 把它当成一个 url ，而不要当成服务名
    sender:
      type: web
  application:
    name: zipkin-client
server:
  port: 9511
